import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const t = {
  en: {
    nav: { dashboard:'Dashboard', menu:'Menu Builder', tables:'Tables & QR', orders:'Orders', analytics:'Analytics', inventory:'Inventory', staff:'Staff', soon:'Soon' },
    common: { add:'Add', edit:'Edit', delete:'Delete', save:'Save', cancel:'Cancel', update:'Update', logout:'Logout', loading:'Loading...', available:'Available', unavailable:'Unavailable', exportCSV:'Export CSV', refresh:'Refresh', apply:'Apply' },
    menu: { title:'Menu Builder', addCategory:'Add Category', editCategory:'Edit Category', addItem:'+ Add Item', editItem:'Edit Item', itemName:'Item Name', itemNamePlaceholder:'e.g. Paneer Tikka or Cluck it Burger!', description:'Description', descPlaceholder:'Describe your dish, or use AI to generate one...', price:'Price', photo:'Photo', uploadPhoto:'Click to upload photo', generateDesc:'Generate with AI', generatingDesc:'Generating...', suggestTags:'Suggest with AI', suggestingTags:'Suggesting...', generateImage:'Generate image with AI', generatingImage:'Generating image...', dietaryTags:'Dietary Tags', modifiers:'Modifiers', addGroup:'+ Add Group', addOption:'+ Add Option', groupName:'Group name (e.g. Size, Add-ons)', optionLabel:'Option label', extraPrice:'+price', noCategories:'No categories yet', noItems:'No items yet — add your first dish!', categoryPlaceholder:'e.g. Starters, Mains, Desserts', aiSuggestedTags:'AI suggested', canDeselect:'you can deselect any below', imageNote:'This may take up to 60 seconds', selectCategory:'Select a category', startWithCategory:'Add a category to get started' },
    inventory: { title:'Inventory', addItem:'+ Add Item', editItem:'Edit Item', bulkEdit:'Bulk Edit', cancelBulk:'Cancel Bulk Edit', saveAll:'Save All', allItems:'All Items', lowStock:'Low Stock', outOfStock:'Out of Stock', unlimited:'Unlimited', inStock:'In Stock', quantity:'Quantity', unit:'Unit', alertThreshold:'Low Stock Alert Threshold', alertWhen:'Alert when ≤', emailAlertSent:'email alert sent', helpText:'Leave stock blank for unlimited. Items at 0 are automatically hidden from the customer menu. Low stock alerts are sent when stock reaches the threshold.', selectUnit:'Select', bulkSaveHint:'Edit stock quantities below then save all at once', outStockMsg:'items are out of stock and hidden from the menu', lowStockMsg:'items are running low — email alert sent' },
    analytics: { title:'Analytics', totalRevenue:'Total Revenue', totalOrders:'Total Orders', avgOrderValue:'Avg Order Value', itemsSold:'Items Sold', revenueChart:'Revenue Over Time', topItems:'Top Items', tablePerf:'Table Performance', peakHours:'Peak Hours', today:'Today', last7:'Last 7 days', last30:'Last 30 days', last90:'Last 90 days', noData:'No data for this period', busiestHour:'Busiest hour', ordersLabel:'orders', fromLabel:'From', toLabel:'To', qtySold:'Qty sold' },
    customer: { selectLang:'Select Language', continueMenu:'Continue to Menu', skipBrowse:'Skip, just browse', enterDetails:"Let's get started!", optionalDetails:'Enter your details for a personalised experience, or skip.', yourName:'Your Name', phoneNumber:'Phone Number', optional:'optional', addToCart:'Add to Cart', viewCart:'View Cart', placeOrder:'Place Order', placing:'Placing Order...', yourCart:'Your Cart', items:'items', orderPlaced:'Order Placed!', orderSentKitchen:"Your order has been sent to the kitchen. We'll have it ready soon!", orderId:'Order ID', orderMore:'Order More', specialInstructions:'Special Instructions', goesWith:'Goes well with...', forYou:'For You', total:'Total', billSummary:'Bill Summary', scanOrder:'Scan to view menu & order', poweredBy:'Powered by QRunch', welcomeBack:'Welcome back', returnMenu:'Returning to menu in', emptyCart:'Your cart is empty', browseMenu:'Browse Menu', yourDetails:'Your Details', reorderNote:'Used for reordering and order updates only.', remove:'Remove', noMenu:'Menu is being prepared. Check back soon!' }
  },

  hi: {
    nav: { dashboard:'डैशबोर्ड', menu:'मेनू बनाएं', tables:'टेबल और QR', orders:'ऑर्डर', analytics:'विश्लेषण', inventory:'भंडार', staff:'स्टाफ', soon:'जल्द' },
    common: { add:'जोड़ें', edit:'संपादित करें', delete:'हटाएं', save:'सहेजें', cancel:'रद्द करें', update:'अपडेट करें', logout:'लॉग आउट', loading:'लोड हो रहा है...', available:'उपलब्ध', unavailable:'अनुपलब्ध', exportCSV:'CSV निर्यात', refresh:'रिफ्रेश', apply:'लागू करें' },
    menu: { title:'मेनू बनाएं', addCategory:'श्रेणी जोड़ें', editCategory:'श्रेणी संपादित करें', addItem:'+ आइटम जोड़ें', editItem:'आइटम संपादित करें', itemName:'आइटम का नाम', itemNamePlaceholder:'जैसे: पनीर टिक्का या बटर चिकन', description:'विवरण', descPlaceholder:'अपने व्यंजन का वर्णन करें...', price:'मूल्य', photo:'फोटो', uploadPhoto:'फोटो अपलोड करें', generateDesc:'AI से बनाएं', generatingDesc:'बन रहा है...', suggestTags:'AI से सुझाएं', suggestingTags:'सुझाव आ रहे हैं...', generateImage:'AI से छवि बनाएं', generatingImage:'छवि बन रही है...', dietaryTags:'आहार टैग', modifiers:'संशोधक', addGroup:'+ समूह जोड़ें', addOption:'+ विकल्प जोड़ें', groupName:'समूह का नाम (जैसे: आकार, ऐड-ऑन)', optionLabel:'विकल्प का नाम', extraPrice:'+मूल्य', noCategories:'कोई श्रेणी नहीं', noItems:'कोई आइटम नहीं — पहला व्यंजन जोड़ें!', categoryPlaceholder:'जैसे: स्टार्टर, मेन कोर्स, डेज़र्ट', aiSuggestedTags:'AI सुझाव', canDeselect:'आप कोई भी हटा सकते हैं', imageNote:'इसमें 60 सेकंड तक लग सकते हैं', selectCategory:'श्रेणी चुनें', startWithCategory:'शुरू करने के लिए श्रेणी जोड़ें' },
    inventory: { title:'भंडार', addItem:'+ आइटम जोड़ें', editItem:'आइटम संपादित करें', bulkEdit:'सभी संपादित करें', cancelBulk:'रद्द करें', saveAll:'सभी सहेजें', allItems:'सभी आइटम', lowStock:'कम स्टॉक', outOfStock:'स्टॉक खत्म', unlimited:'असीमित', inStock:'स्टॉक में', quantity:'मात्रा', unit:'इकाई', alertThreshold:'कम स्टॉक अलर्ट सीमा', alertWhen:'अलर्ट जब ≤', emailAlertSent:'ईमेल अलर्ट भेजा गया', helpText:'असीमित के लिए खाली छोड़ें। 0 पर आइटम मेनू से छुप जाते हैं।', selectUnit:'चुनें', bulkSaveHint:'नीचे मात्रा बदलें फिर एक साथ सहेजें', outStockMsg:'आइटम स्टॉक से बाहर और मेनू से छुपे हुए हैं', lowStockMsg:'आइटम कम हो रहे हैं — ईमेल अलर्ट भेजा गया' },
    analytics: { title:'विश्लेषण', totalRevenue:'कुल आय', totalOrders:'कुल ऑर्डर', avgOrderValue:'औसत ऑर्डर मूल्य', itemsSold:'बिके आइटम', revenueChart:'समय के साथ आय', topItems:'शीर्ष आइटम', tablePerf:'टेबल प्रदर्शन', peakHours:'व्यस्त घंटे', today:'आज', last7:'पिछले 7 दिन', last30:'पिछले 30 दिन', last90:'पिछले 90 दिन', noData:'इस अवधि के लिए कोई डेटा नहीं', busiestHour:'सबसे व्यस्त घंटा', ordersLabel:'ऑर्डर', fromLabel:'से', toLabel:'तक', qtySold:'बिकी मात्रा' },
    customer: { selectLang:'भाषा चुनें', continueMenu:'मेनू पर जाएं', skipBrowse:'सीधे मेनू देखें', enterDetails:'शुरू करते हैं!', optionalDetails:'बेहतर अनुभव के लिए जानकारी दें, या छोड़ें।', yourName:'आपका नाम', phoneNumber:'फोन नंबर', optional:'वैकल्पिक', addToCart:'कार्ट में जोड़ें', viewCart:'कार्ट देखें', placeOrder:'ऑर्डर दें', placing:'ऑर्डर हो रहा है...', yourCart:'आपका कार्ट', items:'आइटम', orderPlaced:'ऑर्डर दे दिया!', orderSentKitchen:'आपका ऑर्डर रसोई को भेज दिया गया है।', orderId:'ऑर्डर ID', orderMore:'और ऑर्डर करें', specialInstructions:'विशेष निर्देश', goesWith:'इसके साथ खाएं...', forYou:'आपके लिए', total:'कुल', billSummary:'बिल सारांश', scanOrder:'मेनू देखें और ऑर्डर करें', poweredBy:'QRunch द्वारा', welcomeBack:'वापस स्वागत', returnMenu:'मेनू पर वापस', emptyCart:'कार्ट खाली है', browseMenu:'मेनू देखें', yourDetails:'आपकी जानकारी', reorderNote:'केवल पुनः ऑर्डर और अपडेट के लिए।', remove:'हटाएं', noMenu:'मेनू तैयार हो रहा है।' }
  },

  mr: {
    nav: { dashboard:'डॅशबोर्ड', menu:'मेनू तयार करा', tables:'टेबल आणि QR', orders:'ऑर्डर', analytics:'विश्लेषण', inventory:'साठा', staff:'कर्मचारी', soon:'लवकरच' },
    common: { add:'जोडा', edit:'संपादित करा', delete:'हटवा', save:'जतन करा', cancel:'रद्द करा', update:'अपडेट करा', logout:'लॉग आउट', loading:'लोड होत आहे...', available:'उपलब्ध', unavailable:'अनुपलब्ध', exportCSV:'CSV निर्यात', refresh:'रिफ्रेश', apply:'लागू करा' },
    menu: { title:'मेनू तयार करा', addCategory:'श्रेणी जोडा', editCategory:'श्रेणी संपादित करा', addItem:'+ आयटम जोडा', editItem:'आयटम संपादित करा', itemName:'आयटमचे नाव', itemNamePlaceholder:'उदा. पनीर टिक्का', description:'वर्णन', descPlaceholder:'तुमच्या पदार्थाचे वर्णन करा...', price:'किंमत', photo:'फोटो', uploadPhoto:'फोटो अपलोड करा', generateDesc:'AI ने तयार करा', generatingDesc:'तयार होत आहे...', suggestTags:'AI ने सुचवा', suggestingTags:'सुचवत आहे...', generateImage:'AI ने चित्र तयार करा', generatingImage:'चित्र तयार होत आहे...', dietaryTags:'आहार टॅग', modifiers:'बदल', addGroup:'+ गट जोडा', addOption:'+ पर्याय जोडा', groupName:'गटाचे नाव', optionLabel:'पर्यायाचे नाव', extraPrice:'+किंमत', noCategories:'अद्याप कोणतीही श्रेणी नाही', noItems:'अद्याप कोणताही आयटम नाही!', categoryPlaceholder:'उदा. स्टार्टर, मेन कोर्स, डेझर्ट', aiSuggestedTags:'AI सुचवण', canDeselect:'आपण कोणतेही काढू शकता', imageNote:'60 सेकंदांपर्यंत वेळ लागू शकतो', selectCategory:'श्रेणी निवडा', startWithCategory:'सुरू करण्यासाठी श्रेणी जोडा' },
    inventory: { title:'साठा', addItem:'+ आयटम जोडा', editItem:'आयटम संपादित करा', bulkEdit:'सर्व संपादित करा', cancelBulk:'रद्द करा', saveAll:'सर्व जतन करा', allItems:'सर्व आयटम', lowStock:'कमी साठा', outOfStock:'साठा संपला', unlimited:'असीमित', inStock:'साठ्यात', quantity:'प्रमाण', unit:'एकक', alertThreshold:'कमी साठा सूचना मर्यादा', alertWhen:'सूचना जेव्हा ≤', emailAlertSent:'ईमेल सूचना पाठवली', helpText:'असीमितसाठी रिकामे ठेवा. 0 वर आयटम मेनूमधून लपतात.', selectUnit:'निवडा', bulkSaveHint:'खाली प्रमाण बदला मग एकत्र जतन करा', outStockMsg:'आयटम साठ्याबाहेर आहेत', lowStockMsg:'आयटम कमी होत आहेत — ईमेल सूचना पाठवली' },
    analytics: { title:'विश्लेषण', totalRevenue:'एकूण उत्पन्न', totalOrders:'एकूण ऑर्डर', avgOrderValue:'सरासरी ऑर्डर मूल्य', itemsSold:'विकले गेलेले आयटम', revenueChart:'वेळानुसार उत्पन्न', topItems:'शीर्ष आयटम', tablePerf:'टेबल कामगिरी', peakHours:'व्यस्त तास', today:'आज', last7:'मागील 7 दिवस', last30:'मागील 30 दिवस', last90:'मागील 90 दिवस', noData:'या कालावधीसाठी डेटा नाही', busiestHour:'सर्वात व्यस्त तास', ordersLabel:'ऑर्डर', fromLabel:'पासून', toLabel:'पर्यंत', qtySold:'विकलेले प्रमाण' },
    customer: { selectLang:'भाषा निवडा', continueMenu:'मेनूकडे जा', skipBrowse:'थेट मेनू पाहा', enterDetails:'सुरुवात करूया!', optionalDetails:'चांगल्या अनुभवासाठी माहिती द्या, किंवा वगळा.', yourName:'तुमचे नाव', phoneNumber:'फोन नंबर', optional:'पर्यायी', addToCart:'कार्टमध्ये जोडा', viewCart:'कार्ट पाहा', placeOrder:'ऑर्डर द्या', placing:'ऑर्डर होत आहे...', yourCart:'तुमची कार्ट', items:'आयटम', orderPlaced:'ऑर्डर दिला!', orderSentKitchen:'तुमचा ऑर्डर स्वयंपाकघरात पाठवला आहे.', orderId:'ऑर्डर ID', orderMore:'आणखी ऑर्डर करा', specialInstructions:'विशेष सूचना', goesWith:'यासोबत खा...', forYou:'तुमच्यासाठी', total:'एकूण', billSummary:'बिल सारांश', scanOrder:'मेनू पाहा आणि ऑर्डर करा', poweredBy:'QRunch द्वारे', welcomeBack:'पुन्हा स्वागत', returnMenu:'मेनूवर परत', emptyCart:'कार्ट रिकामी आहे', browseMenu:'मेनू पाहा', yourDetails:'तुमची माहिती', reorderNote:'फक्त पुनः ऑर्डरसाठी.', remove:'हटवा', noMenu:'मेनू तयार होत आहे.' }
  },

  gu: {
    nav: { dashboard:'ડૅશબૉર્ડ', menu:'મેનૂ બનાવો', tables:'ટેબલ અને QR', orders:'ઓર્ડર', analytics:'વિશ્લેષણ', inventory:'ઇન્વેન્ટરી', staff:'સ્ટાફ', soon:'જલ્દી' },
    common: { add:'ઉમેરો', edit:'સંપાદિત કરો', delete:'કાઢો', save:'સાચવો', cancel:'રદ કરો', update:'અપડેટ કરો', logout:'લૉગ આઉટ', loading:'લોડ થઈ રહ્યું છે...', available:'ઉપલબ્ધ', unavailable:'અનુપલબ્ધ', exportCSV:'CSV નિકાસ', refresh:'રિફ્રેશ', apply:'લાગુ કરો' },
    menu: { title:'મેનૂ બનાવો', addCategory:'કેટેગરી ઉમેરો', editCategory:'કેટેગરી સંપાદિત કરો', addItem:'+ આઇટમ ઉમેરો', editItem:'આઇટમ સંપાદિત કરો', itemName:'આઇટમ નું નામ', itemNamePlaceholder:'દા.ત. પનીર ટિક્કા', description:'વર્ણન', descPlaceholder:'તમારી વાનગી નું વર્ણન કરો...', price:'ભાવ', photo:'ફોટો', uploadPhoto:'ફોટો અપલોડ કરો', generateDesc:'AI થી બનાવો', generatingDesc:'બની રહ્યું છે...', suggestTags:'AI થી સૂચવો', suggestingTags:'સૂચવી રહ્યું છે...', generateImage:'AI થી ચિત્ર બનાવો', generatingImage:'ચિત્ર બની રહ્યું છે...', dietaryTags:'આહાર ટૅગ', modifiers:'ફેરફારો', addGroup:'+ જૂથ ઉમેરો', addOption:'+ વિકલ્પ ઉમેરો', groupName:'જૂથ નું નામ', optionLabel:'વિકલ્પ', extraPrice:'+ભાવ', noCategories:'હજી કોઈ કેટેગરી નથી', noItems:'હજી કોઈ આઇટમ નથી!', categoryPlaceholder:'દા.ત. સ્ટાર્ટર, મેઇન, ડેઝર્ટ', aiSuggestedTags:'AI સૂચન', canDeselect:'તમે કોઈ પણ હટાવી શકો', imageNote:'60 સેકન્ડ સુધી લાગી શકે', selectCategory:'કેટેગરી પસંદ કરો', startWithCategory:'શરૂ કરવા કેટેગરી ઉમેરો' },
    inventory: { title:'ઇન્વેન્ટરી', addItem:'+ આઇટમ ઉમેરો', editItem:'આઇટમ સંપાદિત કરો', bulkEdit:'બધા સંપાદિત કરો', cancelBulk:'રદ કરો', saveAll:'બધા સાચવો', allItems:'બધા આઇટમ', lowStock:'ઓછો સ્ટૉક', outOfStock:'સ્ટૉક ખૂટ્યો', unlimited:'અમર્યાદિત', inStock:'સ્ટૉકમાં', quantity:'જથ્થો', unit:'એકમ', alertThreshold:'ઓછા સ્ટૉક ની ચેતવણી', alertWhen:'ચેતવણી જ્યારે ≤', emailAlertSent:'ઈ-મેઇલ ચેતવણી મોકલી', helpText:'અમર્યાદિત માટે ખાલી છોડો. 0 પર આઇટમ મેનૂ માંથી છૂપાય.', selectUnit:'પસંદ કરો', bulkSaveHint:'નીચે જથ્થો બદલો પછી બધા સાથે સાચવો', outStockMsg:'આઇટમ સ્ટૉક ખૂટ્યો', lowStockMsg:'આઇટમ ઓછા — ઈ-મેઇલ ચેતવણી મોકલી' },
    analytics: { title:'વિશ્લેષણ', totalRevenue:'કુલ આવક', totalOrders:'કુલ ઓર્ડર', avgOrderValue:'સરેરાશ ઓર્ડર મૂલ્ય', itemsSold:'વેચાયેલ આઇટમ', revenueChart:'સમય સાથે આવક', topItems:'ટોચ ના આઇટમ', tablePerf:'ટેબલ પ્રદર્શન', peakHours:'વ્યસ્ત સમય', today:'આજ', last7:'છેલ્લા 7 દિવસ', last30:'છેલ્લા 30 દિવસ', last90:'છેલ્લા 90 દિવસ', noData:'આ સમયગાળા માટે ડેટા નથી', busiestHour:'સૌથી વ્યસ્ત સમય', ordersLabel:'ઓર્ડર', fromLabel:'થી', toLabel:'સુધી', qtySold:'વેચાયેલ જથ્થો' },
    customer: { selectLang:'ભાષા પસંદ કરો', continueMenu:'મેનૂ પર જાઓ', skipBrowse:'સીધા મેનૂ જુઓ', enterDetails:'ચાલો શરૂ કરીએ!', optionalDetails:'સારા અનુભવ માટે માહિતી આપો, અથવા છોડો.', yourName:'તમારું નામ', phoneNumber:'ફોન નંબર', optional:'વૈકલ્પિક', addToCart:'કાર્ટ માં ઉમેરો', viewCart:'કાર્ટ જુઓ', placeOrder:'ઓર્ડર આપો', placing:'ઓર્ડર થઈ રહ્યો છે...', yourCart:'તમારી કાર્ટ', items:'આઇટમ', orderPlaced:'ઓર્ડર આપ્યો!', orderSentKitchen:'તમારો ઓર્ડર રસોઈ ઘરે મોકલ્યો.', orderId:'ઓર્ડર ID', orderMore:'વધુ ઓર્ડર કરો', specialInstructions:'ખાસ સૂચनाઓ', goesWith:'સાથે ખાઓ...', forYou:'તમારા માટે', total:'કુલ', billSummary:'બિલ સારાંश', scanOrder:'મેનૂ જુઓ', poweredBy:'QRunch દ્વારા', welcomeBack:'પાછા સ્વાગત', returnMenu:'મેનૂ પર પાછા', emptyCart:'કાર્ટ ખાલી છે', browseMenu:'મેનૂ જુઓ', yourDetails:'તમારી માહિતી', reorderNote:'ફક્ત પુનઃ ઓર્ડર માટે.', remove:'કાઢો', noMenu:'મેનૂ તૈયાર થઈ રહ્યો છે.' }
  },

  ta: {
    nav: { dashboard:'டாஷ்போர்டு', menu:'மெனு உருவாக்கி', tables:'மேசைகள் மற்றும் QR', orders:'ஆர்டர்கள்', analytics:'பகுப்பாய்வு', inventory:'சரக்கு', staff:'பணியாளர்கள்', soon:'விரைவில்' },
    common: { add:'சேர்', edit:'திருத்து', delete:'நீக்கு', save:'சேமி', cancel:'ரத்துசெய்', update:'புதுப்பி', logout:'வெளியேறு', loading:'ஏற்றுகிறது...', available:'கிடைக்கிறது', unavailable:'கிடைக்கவில்லை', exportCSV:'CSV ஏற்றுமதி', refresh:'புதுப்பி', apply:'பயன்படுத்து' },
    menu: { title:'மெனு உருவாக்கி', addCategory:'வகை சேர்', editCategory:'வகை திருத்து', addItem:'+ உணவு சேர்', editItem:'உணவு திருத்து', itemName:'உணவின் பெயர்', itemNamePlaceholder:'எ.கா. பனீர் டிக்கா', description:'விவரம்', descPlaceholder:'உங்கள் உணவை விவரிக்கவும்...', price:'விலை', photo:'படம்', uploadPhoto:'படம் பதிவேற்று', generateDesc:'AI உடன் உருவாக்கு', generatingDesc:'உருவாக்குகிறது...', suggestTags:'AI பரிந்துரை', suggestingTags:'பரிந்துரைக்கிறது...', generateImage:'AI படம் உருவாக்கு', generatingImage:'படம் உருவாகிறது...', dietaryTags:'உணவு குறிச்சொற்கள்', modifiers:'மாற்றங்கள்', addGroup:'+ குழு சேர்', addOption:'+ விருப்பம் சேர்', groupName:'குழுவின் பெயர்', optionLabel:'விருப்ப பெயர்', extraPrice:'+விலை', noCategories:'வகைகள் இல்லை', noItems:'உணவுகள் இல்லை!', categoryPlaceholder:'எ.கா. முன்னிரு, முதன்மை, இனிப்பு', aiSuggestedTags:'AI பரிந்துரை', canDeselect:'ஏதேனும் நீக்கலாம்', imageNote:'60 வினாடிகள் வரை ஆகலாம்', selectCategory:'வகை தேர்வு', startWithCategory:'தொடங்க வகை சேர்க்கவும்' },
    inventory: { title:'சரக்கு', addItem:'+ பொருள் சேர்', editItem:'பொருள் திருத்து', bulkEdit:'அனைத்தும் திருத்து', cancelBulk:'ரத்துசெய்', saveAll:'அனைத்தும் சேமி', allItems:'அனைத்து பொருட்கள்', lowStock:'குறைந்த சரக்கு', outOfStock:'சரக்கு இல்லை', unlimited:'வரம்பற்றது', inStock:'சரக்கில் உள்ளது', quantity:'அளவு', unit:'அலகு', alertThreshold:'குறைந்த சரக்கு எச்சரிக்கை', alertWhen:'எச்சரிக்கை ≤', emailAlertSent:'மின்னஞ்சல் அனுப்பப்பட்டது', helpText:'வரம்பற்றதற்கு காலியாக விடுங்கள். 0 இல் மெனுவில் இருந்து மறைகிறது.', selectUnit:'தேர்வு', bulkSaveHint:'கீழே அளவை மாற்றி ஒரே நேரத்தில் சேமிக்கவும்', outStockMsg:'பொருட்கள் சரக்கு இல்லை', lowStockMsg:'பொருட்கள் குறைகின்றன — மின்னஞ்சல் அனுப்பப்பட்டது' },
    analytics: { title:'பகுப்பாய்வு', totalRevenue:'மொத்த வருவாய்', totalOrders:'மொத்த ஆர்டர்கள்', avgOrderValue:'சராசரி ஆர்டர் மதிப்பு', itemsSold:'விற்கப்பட்ட பொருட்கள்', revenueChart:'காலப்போக்கில் வருவாய்', topItems:'சிறந்த பொருட்கள்', tablePerf:'மேசை செயல்திறன்', peakHours:'பரபரப்பான நேரம்', today:'இன்று', last7:'கடந்த 7 நாட்கள்', last30:'கடந்த 30 நாட்கள்', last90:'கடந்த 90 நாட்கள்', noData:'இந்த காலகட்டத்தில் தரவு இல்லை', busiestHour:'மிகவும் பரபரப்பான நேரம்', ordersLabel:'ஆர்டர்கள்', fromLabel:'இருந்து', toLabel:'வரை', qtySold:'விற்ற அளவு' },
    customer: { selectLang:'மொழி தேர்வு', continueMenu:'மெனுவிற்கு செல்', skipBrowse:'நேரடியாக மெனு', enterDetails:'தொடங்குவோம்!', optionalDetails:'சிறந்த அனுபவத்திற்கு தகவல் கொடுங்கள்.', yourName:'உங்கள் பெயர்', phoneNumber:'தொலைபேசி எண்', optional:'விருப்பத்தேர்வு', addToCart:'கார்ட்டில் சேர்', viewCart:'கார்ட் பார்', placeOrder:'ஆர்டர் கொடு', placing:'ஆர்டர் ஆகிறது...', yourCart:'உங்கள் கார்ட்', items:'பொருட்கள்', orderPlaced:'ஆர்டர் கொடுக்கப்பட்டது!', orderSentKitchen:'உங்கள் ஆர்டர் சமையலறைக்கு அனுப்பப்பட்டது.', orderId:'ஆர்டர் ID', orderMore:'மேலும் ஆர்டர்', specialInstructions:'சிறப்பு வழிமுறைகள்', goesWith:'இதனுடன் சேர்த்து...', forYou:'உங்களுக்காக', total:'மொத்தம்', billSummary:'பில் சுருக்கம்', scanOrder:'ஸ்கேன் செய்து ஆர்டர்', poweredBy:'QRunch ஆல்', welcomeBack:'மீண்டும் வரவேற்கிறோம்', returnMenu:'மெனுவிற்கு திரும்புகிறது', emptyCart:'கார்ட் காலியாக உள்ளது', browseMenu:'மெனு பார்', yourDetails:'உங்கள் விவரங்கள்', reorderNote:'மீண்டும் ஆர்டருக்கு மட்டும்.', remove:'நீக்கு', noMenu:'மெனு தயாராகிறது.' }
  },

  te: {
    nav: { dashboard:'డాష్‌బోర్డ్', menu:'మెనూ బిల్డర్', tables:'టేబుల్స్ మరియు QR', orders:'ఆర్డర్లు', analytics:'విశ్లేషణ', inventory:'జాబితా', staff:'సిబ్బంది', soon:'త్వరలో' },
    common: { add:'జోడించు', edit:'సవరించు', delete:'తొలగించు', save:'సేవ్', cancel:'రద్దు', update:'నవీకరించు', logout:'లాగ్ అవుట్', loading:'లోడ్ అవుతోంది...', available:'అందుబాటులో', unavailable:'అందుబాటులో లేదు', exportCSV:'CSV ఎగుమతి', refresh:'రిఫ్రెష్', apply:'వర్తింపజేయి' },
    menu: { title:'మెనూ బిల్డర్', addCategory:'వర్గం జోడించు', editCategory:'వర్గం సవరించు', addItem:'+ ఐటమ్ జోడించు', editItem:'ఐటమ్ సవరించు', itemName:'ఐటమ్ పేరు', itemNamePlaceholder:'ఉదా: పనీర్ టిక్కా', description:'వివరణ', descPlaceholder:'మీ వంటకం గురించి వివరించండి...', price:'ధర', photo:'ఫోటో', uploadPhoto:'ఫోటో అప్‌లోడ్ చేయి', generateDesc:'AI తో రూపొందించు', generatingDesc:'రూపొందిస్తోంది...', suggestTags:'AI సూచన', suggestingTags:'సూచిస్తోంది...', generateImage:'AI చిత్రం రూపొందించు', generatingImage:'చిత్రం రూపొందిస్తోంది...', dietaryTags:'ఆహార ట్యాగ్‌లు', modifiers:'మార్పులు', addGroup:'+ గ్రూప్ జోడించు', addOption:'+ ఆప్షన్ జోడించు', groupName:'గ్రూప్ పేరు', optionLabel:'ఆప్షన్ పేరు', extraPrice:'+ధర', noCategories:'వర్గాలు లేవు', noItems:'ఐటమ్‌లు లేవు!', categoryPlaceholder:'ఉదా: స్టార్టర్, మెయిన్, డెజర్ట్', aiSuggestedTags:'AI సూచన', canDeselect:'ఏదైనా తీసివేయవచ్చు', imageNote:'60 సెకన్లు పట్టవచ్చు', selectCategory:'వర్గం ఎంచుకో', startWithCategory:'వర్గం జోడించి ప్రారంభించు' },
    inventory: { title:'జాబితా', addItem:'+ అంశం జోడించు', editItem:'అంశం సవరించు', bulkEdit:'అన్నీ సవరించు', cancelBulk:'రద్దు', saveAll:'అన్నీ సేవ్ చేయి', allItems:'అన్ని అంశాలు', lowStock:'తక్కువ స్టాక్', outOfStock:'స్టాక్ లేదు', unlimited:'అపరిమితం', inStock:'స్టాక్‌లో ఉంది', quantity:'పరిమాణం', unit:'యూనిట్', alertThreshold:'తక్కువ స్టాక్ హెచ్చరిక', alertWhen:'హెచ్చరిక ≤', emailAlertSent:'ఇమెయిల్ పంపబడింది', helpText:'అపరిమితంగా ఖాళీగా వదలండి. 0 వద్ద మెనూ నుండి దాగుతుంది.', selectUnit:'ఎంచుకో', bulkSaveHint:'కింద పరిమాణం మార్చి ఒకేసారి సేవ్ చేయి', outStockMsg:'అంశాలు స్టాక్ లేవు', lowStockMsg:'అంశాలు తగ్గుతున్నాయి — ఇమెయిల్ పంపబడింది' },
    analytics: { title:'విశ్లేషణ', totalRevenue:'మొత్తం ఆదాయం', totalOrders:'మొత్తం ఆర్డర్లు', avgOrderValue:'సగటు ఆర్డర్ విలువ', itemsSold:'అమ్మిన అంశాలు', revenueChart:'కాలక్రమేణా ఆదాయం', topItems:'అగ్రశ్రేణి అంశాలు', tablePerf:'టేబుల్ పనితీరు', peakHours:'బిజీ గంటలు', today:'ఈరోజు', last7:'గత 7 రోజులు', last30:'గత 30 రోజులు', last90:'గత 90 రోజులు', noData:'ఈ కాలానికి డేటా లేదు', busiestHour:'అత్యంత బిజీ గంట', ordersLabel:'ఆర్డర్లు', fromLabel:'నుండి', toLabel:'వరకు', qtySold:'అమ్మిన పరిమాణం' },
    customer: { selectLang:'భాష ఎంచుకోండి', continueMenu:'మెనూకు వెళ్ళు', skipBrowse:'నేరుగా మెనూ', enterDetails:'మొదలుపెట్టండి!', optionalDetails:'మెరుగైన అనుభవానికి వివరాలు ఇవ్వండి.', yourName:'మీ పేరు', phoneNumber:'ఫోన్ నంబర్', optional:'ఐచ్ఛికం', addToCart:'కార్ట్‌కు జోడించు', viewCart:'కార్ట్ చూడు', placeOrder:'ఆర్డర్ ఇవ్వు', placing:'ఆర్డర్ అవుతోంది...', yourCart:'మీ కార్ట్', items:'అంశాలు', orderPlaced:'ఆర్డర్ ఇవ్వబడింది!', orderSentKitchen:'మీ ఆర్డర్ వంటిల్లుకు పంపబడింది.', orderId:'ఆర్డర్ ID', orderMore:'మరిన్ని ఆర్డర్', specialInstructions:'ప్రత్యేక సూచనలు', goesWith:'దీనితో...', forYou:'మీ కోసం', total:'మొత్తం', billSummary:'బిల్ సారాంశం', scanOrder:'స్కాన్ చేసి ఆర్డర్', poweredBy:'QRunch ద్వారా', welcomeBack:'తిరిగి స్వాగతం', returnMenu:'మెనూకు తిరిగి', emptyCart:'కార్ట్ ఖాళీగా ఉంది', browseMenu:'మెనూ చూడు', yourDetails:'మీ వివరాలు', reorderNote:'తిరిగి ఆర్డర్‌కు మాత్రమే.', remove:'తొలగించు', noMenu:'మెనూ సిద్ధమవుతోంది.' }
  },

  ml: {
    nav: { dashboard:'ഡാഷ്ബോർഡ്', menu:'മെനു ബിൽഡർ', tables:'ടേബിളുകളും QR', orders:'ഓർഡറുകൾ', analytics:'അനലിറ്റിക്സ്', inventory:'ഇൻവെന്ററി', staff:'ജീവനക്കാർ', soon:'ഉടൻ' },
    common: { add:'ചേർക്കുക', edit:'എഡിറ്റ്', delete:'ഇല്ലാതാക്കുക', save:'സേവ്', cancel:'റദ്ദാക്കുക', update:'അപ്ഡേറ്റ്', logout:'ലോഗ് ഔട്ട്', loading:'ലോഡ്...', available:'ലഭ്യം', unavailable:'ലഭ്യമല്ല', exportCSV:'CSV കയറ്റുമതി', refresh:'പുതുക്കുക', apply:'പ്രയോഗിക്കുക' },
    menu: { title:'മെനു ബിൽഡർ', addCategory:'വിഭാഗം ചേർക്കുക', editCategory:'വിഭാഗം എഡിറ്റ്', addItem:'+ ഇനം ചേർക്കുക', editItem:'ഇനം എഡിറ്റ്', itemName:'ഇനത്തിന്റെ പേര്', itemNamePlaceholder:'ഉദാ: പനീർ ടിക്ക', description:'വിവരണം', descPlaceholder:'വിഭവം വിവരിക്കുക...', price:'വില', photo:'ഫോട്ടോ', uploadPhoto:'ഫോട്ടോ അപ്‌ലോഡ്', generateDesc:'AI ഉണ്ടാക്കുക', generatingDesc:'ഉണ്ടാക്കുന്നു...', suggestTags:'AI നിർദ്ദേശം', suggestingTags:'നിർദ്ദേശിക്കുന്നു...', generateImage:'AI ചിത്രം', generatingImage:'ചിത്രം ഉണ്ടാക്കുന്നു...', dietaryTags:'ഭക്ഷണ ടാഗുകൾ', modifiers:'മാറ്റങ്ങൾ', addGroup:'+ ഗ്രൂപ്പ് ചേർക്കുക', addOption:'+ ഓപ്ഷൻ ചേർക്കുക', groupName:'ഗ്രൂപ്പ് പേര്', optionLabel:'ഓപ്ഷൻ പേര്', extraPrice:'+വില', noCategories:'വിഭാഗങ്ങൾ ഇല്ല', noItems:'ഇനങ്ങൾ ഇല്ല!', categoryPlaceholder:'ഉദാ: സ്റ്റാർട്ടർ, മെയിൻ, ഡെസേർട്ട്', aiSuggestedTags:'AI നിർദ്ദേശം', canDeselect:'ഏതും നീക്കാം', imageNote:'60 സെക്കൻഡ് വരെ ഉണ്ടാകാം', selectCategory:'വിഭാഗം തിരഞ്ഞെടുക്കുക', startWithCategory:'ആരംഭിക്കാൻ വിഭാഗം ചേർക്കുക' },
    inventory: { title:'ഇൻവെന്ററി', addItem:'+ ഇനം ചേർക്കുക', editItem:'ഇനം എഡിറ്റ്', bulkEdit:'എല്ലാം എഡിറ്റ്', cancelBulk:'റദ്ദാക്കുക', saveAll:'എല്ലാം സേവ്', allItems:'എല്ലാ ഇനങ്ങൾ', lowStock:'കുറഞ്ഞ സ്റ്റോക്ക്', outOfStock:'സ്റ്റോക്ക് ഇല്ല', unlimited:'അപരിമിതം', inStock:'സ്റ്റോക്കിൽ', quantity:'അളവ്', unit:'യൂണിറ്റ്', alertThreshold:'കുറഞ്ഞ സ്റ്റോക്ക് മുന്നറിയിപ്പ്', alertWhen:'മുന്നറിയിപ്പ് ≤', emailAlertSent:'ഇമെയിൽ അയച്ചു', helpText:'അപരിമിതത്തിന് ഒഴിച്ചിടുക. 0-ൽ മെനുവിൽ നിന്ന് മറയ്ക്കുന്നു.', selectUnit:'തിരഞ്ഞെടുക്കുക', bulkSaveHint:'താഴെ അളവ് മാറ്റി ഒരുമിച്ച് സേവ് ചെയ്യുക', outStockMsg:'ഇനങ്ങൾ സ്റ്റോക്കില്ല', lowStockMsg:'ഇനങ്ങൾ കുറയുന്നു — ഇമെയിൽ അയച്ചു' },
    analytics: { title:'അനലിറ്റിക്സ്', totalRevenue:'ആകെ വരുമാനം', totalOrders:'ആകെ ഓർഡറുകൾ', avgOrderValue:'ശരാശരി ഓർഡർ മൂല്യം', itemsSold:'വിറ്റ ഇനങ്ങൾ', revenueChart:'കാലക്രമേണ വരുമാനം', topItems:'മികച്ച ഇനങ്ങൾ', tablePerf:'ടേബിൾ പ്രകടനം', peakHours:'തിരക്കേറിയ സമയം', today:'ഇന്ന്', last7:'കഴിഞ്ഞ 7 ദിവസം', last30:'കഴിഞ്ഞ 30 ദിവസം', last90:'കഴിഞ്ഞ 90 ദിവസം', noData:'ഈ കാലയളവിൽ ഡേറ്റ ഇല്ല', busiestHour:'ഏറ്റവും തിരക്കേറിയ സമയം', ordersLabel:'ഓർഡറുകൾ', fromLabel:'മുതൽ', toLabel:'വരെ', qtySold:'വിറ്റ അളവ്' },
    customer: { selectLang:'ഭാഷ തിരഞ്ഞെടുക്കുക', continueMenu:'മെനൂ വഴി', skipBrowse:'നേരിട്ട് മെനൂ', enterDetails:'തുടങ്ങാം!', optionalDetails:'നല്ല അനുഭവത്തിന് വിവരങ്ങൾ നൽകുക.', yourName:'പേര്', phoneNumber:'ഫോൺ നമ്പർ', optional:'ഐച്ഛികം', addToCart:'കാർട്ടിൽ ചേർക്കുക', viewCart:'കാർട്ട് കാണുക', placeOrder:'ഓർഡർ നൽകുക', placing:'ഓർഡർ ആകുന്നു...', yourCart:'കാർട്ട്', items:'ഇനങ്ങൾ', orderPlaced:'ഓർഡർ നൽകി!', orderSentKitchen:'ഓർഡർ അടുക്കളയിലേക്ക് അയച്ചു.', orderId:'ഓർഡർ ID', orderMore:'കൂടുതൽ ഓർഡർ', specialInstructions:'പ്രത്യേക നിർദേശങ്ങൾ', goesWith:'ഇതിനൊപ്പം...', forYou:'നിങ്ങൾക്കായി', total:'ആകെ', billSummary:'ബിൽ സംഗ്രഹം', scanOrder:'സ്കാൻ ചെയ്ത് ഓർഡർ', poweredBy:'QRunch', welcomeBack:'സ്വാഗതം', returnMenu:'മെനൂ', emptyCart:'കാർട്ട് ഒഴിഞ്ഞിരിക്കുന്നു', browseMenu:'മെനൂ കാണുക', yourDetails:'വിവരങ്ങൾ', reorderNote:'ഓർഡർ അപ്ഡേറ്റിന് മാത്രം.', remove:'നീക്കം', noMenu:'മെനൂ തയ്യാറാകുന്നു.' }
  },

  kn: {
    nav: { dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', menu:'ಮೆನು ಬಿಲ್ಡರ್', tables:'ಟೇಬಲ್ ಮತ್ತು QR', orders:'ಆದೇಶಗಳು', analytics:'ವಿಶ್ಲೇಷಣೆ', inventory:'ದಾಸ್ತಾನು', staff:'ಸಿಬ್ಬಂದಿ', soon:'ಶೀಘ್ರದಲ್ಲಿ' },
    common: { add:'ಸೇರಿಸು', edit:'ಸಂಪಾದಿಸು', delete:'ಅಳಿಸು', save:'ಉಳಿಸು', cancel:'ರದ್ದು', update:'ನವೀಕರಿಸು', logout:'ಲಾಗ್ ಔಟ್', loading:'ಲೋಡ್...', available:'ಲಭ್ಯ', unavailable:'ಲಭ್ಯವಿಲ್ಲ', exportCSV:'CSV ರಫ್ತು', refresh:'ರಿಫ್ರೆಶ್', apply:'ಅನ್ವಯಿಸು' },
    menu: { title:'ಮೆನು ಬಿಲ್ಡರ್', addCategory:'ವರ್ಗ ಸೇರಿಸು', editCategory:'ವರ್ಗ ಸಂಪಾದಿಸು', addItem:'+ ಐಟಮ್ ಸೇರಿಸು', editItem:'ಐಟಮ್ ಸಂಪಾದಿಸು', itemName:'ಐಟಮ್ ಹೆಸರು', itemNamePlaceholder:'ಉದಾ: ಪನೀರ್ ಟಿಕ್ಕಾ', description:'ವಿವರಣೆ', descPlaceholder:'ನಿಮ್ಮ ಭಕ್ಷ್ಯ ವಿವರಿಸಿ...', price:'ಬೆಲೆ', photo:'ಫೋಟೋ', uploadPhoto:'ಫೋಟೋ ಅಪ್ಲೋಡ್', generateDesc:'AI ರಚಿಸು', generatingDesc:'ರಚಿಸುತ್ತಿದೆ...', suggestTags:'AI ಸೂಚಿಸು', suggestingTags:'ಸೂಚಿಸುತ್ತಿದೆ...', generateImage:'AI ಚಿತ್ರ', generatingImage:'ಚಿತ್ರ ರಚಿಸುತ್ತಿದೆ...', dietaryTags:'ಆಹಾರ ಟ್ಯಾಗ್‌ಗಳು', modifiers:'ಬದಲಾವಣೆಗಳು', addGroup:'+ ಗ್ರೂಪ್ ಸೇರಿಸು', addOption:'+ ಆಯ್ಕೆ ಸೇರಿಸು', groupName:'ಗ್ರೂಪ್ ಹೆಸರು', optionLabel:'ಆಯ್ಕೆ ಹೆಸರು', extraPrice:'+ಬೆಲೆ', noCategories:'ವರ್ಗಗಳಿಲ್ಲ', noItems:'ಐಟಮ್‌ಗಳಿಲ್ಲ!', categoryPlaceholder:'ಉದಾ: ಸ್ಟಾರ್ಟರ್, ಮೇನ್, ಡೆಸರ್ಟ್', aiSuggestedTags:'AI ಸೂಚನೆ', canDeselect:'ಯಾವುದನ್ನಾದರೂ ತೆಗೆಯಬಹುದು', imageNote:'60 ಸೆಕೆಂಡ್ ತನಕ ಬೇಕಾಗಬಹುದು', selectCategory:'ವರ್ಗ ಆಯ್ಕೆ', startWithCategory:'ಪ್ರಾರಂಭಿಸಲು ವರ್ಗ ಸೇರಿಸಿ' },
    inventory: { title:'ದಾಸ್ತಾನು', addItem:'+ ವಸ್ತು ಸೇರಿಸು', editItem:'ವಸ್ತು ಸಂಪಾದಿಸು', bulkEdit:'ಎಲ್ಲ ಸಂಪಾದಿಸು', cancelBulk:'ರದ್ದು', saveAll:'ಎಲ್ಲ ಉಳಿಸು', allItems:'ಎಲ್ಲ ವಸ್ತುಗಳು', lowStock:'ಕಡಿಮೆ ಸ್ಟಾಕ್', outOfStock:'ಸ್ಟಾಕ್ ಇಲ್ಲ', unlimited:'ಅಪರಿಮಿತ', inStock:'ಸ್ಟಾಕ್‌ನಲ್ಲಿ', quantity:'ಪ್ರಮಾಣ', unit:'ಏಕಮಾನ', alertThreshold:'ಕಡಿಮೆ ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ', alertWhen:'ಎಚ್ಚರಿಕೆ ≤', emailAlertSent:'ಇಮೇಲ್ ಕಳುಹಿಸಲಾಗಿದೆ', helpText:'ಅಪರಿಮಿತಕ್ಕೆ ಖಾಲಿ ಬಿಡಿ. 0 ರಲ್ಲಿ ಮೆನುನಿಂದ ಮರೆಯಾಗುತ್ತದೆ.', selectUnit:'ಆಯ್ಕೆ ಮಾಡಿ', bulkSaveHint:'ಕೆಳಗೆ ಪ್ರಮಾಣ ಬದಲಾಯಿಸಿ ಒಟ್ಟಿಗೆ ಉಳಿಸಿ', outStockMsg:'ವಸ್ತುಗಳು ಸ್ಟಾಕ್ ಇಲ್ಲ', lowStockMsg:'ವಸ್ತುಗಳು ಕಡಿಮೆ — ಇಮೇಲ್ ಕಳುಹಿಸಲಾಗಿದೆ' },
    analytics: { title:'ವಿಶ್ಲೇಷಣೆ', totalRevenue:'ಒಟ್ಟು ಆದಾಯ', totalOrders:'ಒಟ್ಟು ಆದೇಶಗಳು', avgOrderValue:'ಸರಾಸರಿ ಆದೇಶ ಮೌಲ್ಯ', itemsSold:'ಮಾರಿದ ವಸ್ತುಗಳು', revenueChart:'ಕಾಲಕ್ರಮೇಣ ಆದಾಯ', topItems:'ಅಗ್ರ ವಸ್ತುಗಳು', tablePerf:'ಟೇಬಲ್ ಕಾರ್ಯಕ್ಷಮತೆ', peakHours:'ಗಡಿಬಿಡಿ ಸಮಯ', today:'ಇಂದು', last7:'ಕಳೆದ 7 ದಿನ', last30:'ಕಳೆದ 30 ದಿನ', last90:'ಕಳೆದ 90 ದಿನ', noData:'ಈ ಅವಧಿಗೆ ಡೇಟಾ ಇಲ್ಲ', busiestHour:'ಅತ್ಯಂತ ಗಡಿಬಿಡಿ ಸಮಯ', ordersLabel:'ಆದೇಶಗಳು', fromLabel:'ದಿಂದ', toLabel:'ವರೆಗೆ', qtySold:'ಮಾರಿದ ಪ್ರಮಾಣ' },
    customer: { selectLang:'ಭಾಷೆ ಆಯ್ಕೆ', continueMenu:'ಮೆನುಗೆ ಹೋಗಿ', skipBrowse:'ನೇರ ಮೆನು', enterDetails:'ಪ್ರಾರಂಭಿಸೋಣ!', optionalDetails:'ಉತ್ತಮ ಅನುಭವಕ್ಕೆ ಮಾಹಿತಿ ನೀಡಿ.', yourName:'ಹೆಸರು', phoneNumber:'ಫೋನ್ ನಂಬರ್', optional:'ಐಚ್ಛಿಕ', addToCart:'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ', viewCart:'ಕಾರ್ಟ್ ನೋಡಿ', placeOrder:'ಆರ್ಡರ್ ನೀಡಿ', placing:'ಆರ್ಡರ್ ಆಗುತ್ತಿದೆ...', yourCart:'ಕಾರ್ಟ್', items:'ಐಟಮ್‌ಗಳು', orderPlaced:'ಆರ್ಡರ್ ನೀಡಲಾಗಿದೆ!', orderSentKitchen:'ಆರ್ಡರ್ ಅಡುಗೆಮನೆಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.', orderId:'ಆರ್ಡರ್ ID', orderMore:'ಇನ್ನಷ್ಟು ಆರ್ಡರ್', specialInstructions:'ವಿಶೇಷ ಸೂಚನೆ', goesWith:'ಜೊತೆಯಲ್ಲಿ...', forYou:'ನಿಮಗಾಗಿ', total:'ಒಟ್ಟು', billSummary:'ಬಿಲ್ ಸಾರಾಂಶ', scanOrder:'ಸ್ಕ್ಯಾನ್ ಮಾಡಿ', poweredBy:'QRunch', welcomeBack:'ಸ್ವಾಗತ', returnMenu:'ಮೆನು', emptyCart:'ಕಾರ್ಟ್ ಖಾಲಿ', browseMenu:'ಮೆನು ನೋಡಿ', yourDetails:'ವಿವರಗಳು', reorderNote:'ಮರು ಆರ್ಡರ್‌ಗೆ ಮಾತ್ರ.', remove:'ತೆಗೆ', noMenu:'ಮೆನು ಸಿದ್ಧವಾಗುತ್ತಿದೆ.' }
  },

  bn: {
    nav: { dashboard:'ড্যাশবোর্ড', menu:'মেনু বিল্ডার', tables:'টেবিল এবং QR', orders:'অর্ডার', analytics:'বিশ্লেষণ', inventory:'ইনভেন্টরি', staff:'কর্মী', soon:'শীঘ্রই' },
    common: { add:'যোগ', edit:'সম্পাদনা', delete:'মুছুন', save:'সংরক্ষণ', cancel:'বাতিল', update:'আপডেট', logout:'লগ আউট', loading:'লোড হচ্ছে...', available:'উপলব্ধ', unavailable:'অনুপলব্ধ', exportCSV:'CSV রপ্তানি', refresh:'রিফ্রেশ', apply:'প্রয়োগ' },
    menu: { title:'মেনু বিল্ডার', addCategory:'বিভাগ যোগ করুন', editCategory:'বিভাগ সম্পাদনা', addItem:'+ আইটেম যোগ করুন', editItem:'আইটেম সম্পাদনা', itemName:'আইটেমের নাম', itemNamePlaceholder:'যেমন: পনির টিক্কা', description:'বিবরণ', descPlaceholder:'আপনার রান্না বর্ণনা করুন...', price:'মূল্য', photo:'ছবি', uploadPhoto:'ছবি আপলোড', generateDesc:'AI দিয়ে তৈরি করুন', generatingDesc:'তৈরি হচ্ছে...', suggestTags:'AI পরামর্শ', suggestingTags:'পরামর্শ দিচ্ছে...', generateImage:'AI ছবি তৈরি', generatingImage:'ছবি তৈরি হচ্ছে...', dietaryTags:'খাদ্য ট্যাগ', modifiers:'পরিবর্তন', addGroup:'+ গ্রুপ যোগ', addOption:'+ বিকল্প যোগ', groupName:'গ্রুপের নাম', optionLabel:'বিকল্পের নাম', extraPrice:'+মূল্য', noCategories:'কোনো বিভাগ নেই', noItems:'কোনো আইটেম নেই!', categoryPlaceholder:'যেমন: স্টার্টার, মেইন, ডেজার্ট', aiSuggestedTags:'AI পরামর্শ', canDeselect:'যেকোনো সরাতে পারেন', imageNote:'৬০ সেকেন্ড পর্যন্ত লাগতে পারে', selectCategory:'বিভাগ বেছে নিন', startWithCategory:'শুরু করতে বিভাগ যোগ করুন' },
    inventory: { title:'ইনভেন্টরি', addItem:'+ উপাদান যোগ', editItem:'উপাদান সম্পাদনা', bulkEdit:'সব সম্পাদনা', cancelBulk:'বাতিল', saveAll:'সব সংরক্ষণ', allItems:'সব উপাদান', lowStock:'কম স্টক', outOfStock:'স্টক শেষ', unlimited:'অসীমিত', inStock:'স্টকে আছে', quantity:'পরিমাণ', unit:'একক', alertThreshold:'কম স্টক সতর্কতা', alertWhen:'সতর্কতা ≤', emailAlertSent:'ইমেইল পাঠানো হয়েছে', helpText:'অসীমিতের জন্য ফাঁকা রাখুন। ০-তে মেনু থেকে লুকায়।', selectUnit:'বেছে নিন', bulkSaveHint:'নিচে পরিমাণ পরিবর্তন করুন তারপর একসাথে সংরক্ষণ', outStockMsg:'উপাদান স্টক নেই', lowStockMsg:'উপাদান কম — ইমেইল পাঠানো হয়েছে' },
    analytics: { title:'বিশ্লেষণ', totalRevenue:'মোট আয়', totalOrders:'মোট অর্ডার', avgOrderValue:'গড় অর্ডার মূল্য', itemsSold:'বিক্রিত আইটেম', revenueChart:'সময়ের সাথে আয়', topItems:'শীর্ষ আইটেম', tablePerf:'টেবিল পারফরম্যান্স', peakHours:'ব্যস্ত ঘন্টা', today:'আজ', last7:'গত ৭ দিন', last30:'গত ৩০ দিন', last90:'গত ৯০ দিন', noData:'এই সময়ের জন্য ডেটা নেই', busiestHour:'সবচেয়ে ব্যস্ত ঘন্টা', ordersLabel:'অর্ডার', fromLabel:'থেকে', toLabel:'পর্যন্ত', qtySold:'বিক্রিত পরিমাণ' },
    customer: { selectLang:'ভাষা বেছে নিন', continueMenu:'মেনুতে যান', skipBrowse:'সরাসরি মেনু', enterDetails:'শুরু করা যাক!', optionalDetails:'ভালো অভিজ্ঞতার জন্য তথ্য দিন।', yourName:'নাম', phoneNumber:'ফোন নম্বর', optional:'ঐচ্ছিক', addToCart:'কার্টে যোগ', viewCart:'কার্ট দেখুন', placeOrder:'অর্ডার করুন', placing:'অর্ডার হচ্ছে...', yourCart:'কার্ট', items:'আইটেম', orderPlaced:'অর্ডার দেওয়া হয়েছে!', orderSentKitchen:'অর্ডার রান্নাঘরে পাঠানো হয়েছে।', orderId:'অর্ডার ID', orderMore:'আরো অর্ডার', specialInstructions:'বিশেষ নির্দেশনা', goesWith:'সাথে ভালো...', forYou:'আপনার জন্য', total:'মোট', billSummary:'বিল সারসংক্ষেপ', scanOrder:'স্ক্যান করুন', poweredBy:'QRunch', welcomeBack:'স্বাগতম', returnMenu:'মেনু', emptyCart:'কার্ট খালি', browseMenu:'মেনু দেখুন', yourDetails:'বিবরণ', reorderNote:'পুনরায় অর্ডারের জন্য।', remove:'মুছুন', noMenu:'মেনু প্রস্তুত হচ্ছে।' }
  },

  pa: {
    nav: { dashboard:'ਡੈਸ਼ਬੋਰਡ', menu:'ਮੇਨੂ ਬਿਲਡਰ', tables:'ਟੇਬਲ ਅਤੇ QR', orders:'ਆਰਡਰ', analytics:'ਵਿਸ਼ਲੇਸ਼ਣ', inventory:'ਇਨਵੈਂਟਰੀ', staff:'ਸਟਾਫ਼', soon:'ਜਲਦੀ' },
    common: { add:'ਜੋੜੋ', edit:'ਸੰਪਾਦਿਤ ਕਰੋ', delete:'ਹਟਾਓ', save:'ਸੇਵ', cancel:'ਰੱਦ', update:'ਅਪਡੇਟ', logout:'ਲੌਗ ਆਉਟ', loading:'ਲੋਡ ਹੋ ਰਿਹਾ...', available:'ਉਪਲਬਧ', unavailable:'ਅਣਉਪਲਬਧ', exportCSV:'CSV ਨਿਰਯਾਤ', refresh:'ਰਿਫ੍ਰੈਸ਼', apply:'ਲਾਗੂ ਕਰੋ' },
    menu: { title:'ਮੇਨੂ ਬਿਲਡਰ', addCategory:'ਸ਼੍ਰੇਣੀ ਜੋੜੋ', editCategory:'ਸ਼੍ਰੇਣੀ ਸੰਪਾਦਿਤ ਕਰੋ', addItem:'+ ਆਈਟਮ ਜੋੜੋ', editItem:'ਆਈਟਮ ਸੰਪਾਦਿਤ ਕਰੋ', itemName:'ਆਈਟਮ ਦਾ ਨਾਮ', itemNamePlaceholder:'ਜਿਵੇਂ: ਪਨੀਰ ਟਿੱਕਾ', description:'ਵੇਰਵਾ', descPlaceholder:'ਆਪਣੇ ਖਾਣੇ ਦਾ ਵੇਰਵਾ ਦਿਓ...', price:'ਕੀਮਤ', photo:'ਫੋਟੋ', uploadPhoto:'ਫੋਟੋ ਅਪਲੋਡ ਕਰੋ', generateDesc:'AI ਨਾਲ ਬਣਾਓ', generatingDesc:'ਬਣਾਇਆ ਜਾ ਰਿਹਾ...', suggestTags:'AI ਸੁਝਾਅ', suggestingTags:'ਸੁਝਾਅ ਦਿੱਤੇ ਜਾ ਰਹੇ...', generateImage:'AI ਤਸਵੀਰ', generatingImage:'ਤਸਵੀਰ ਬਣਾਈ ਜਾ ਰਹੀ...', dietaryTags:'ਖੁਰਾਕ ਟੈਗ', modifiers:'ਬਦਲਾਅ', addGroup:'+ ਗਰੁੱਪ ਜੋੜੋ', addOption:'+ ਵਿਕਲਪ ਜੋੜੋ', groupName:'ਗਰੁੱਪ ਨਾਮ', optionLabel:'ਵਿਕਲਪ ਨਾਮ', extraPrice:'+ਕੀਮਤ', noCategories:'ਕੋਈ ਸ਼੍ਰੇਣੀ ਨਹੀਂ', noItems:'ਕੋਈ ਆਈਟਮ ਨਹੀਂ!', categoryPlaceholder:'ਜਿਵੇਂ: ਸਟਾਰਟਰ, ਮੇਨ, ਡੈਜ਼ਰਟ', aiSuggestedTags:'AI ਸੁਝਾਅ', canDeselect:'ਕੋਈ ਵੀ ਹਟਾ ਸਕਦੇ', imageNote:'60 ਸਕਿੰਟ ਤੱਕ ਲੱਗ ਸਕਦੇ', selectCategory:'ਸ਼੍ਰੇਣੀ ਚੁਣੋ', startWithCategory:'ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਸ਼੍ਰੇਣੀ ਜੋੜੋ' },
    inventory: { title:'ਇਨਵੈਂਟਰੀ', addItem:'+ ਸਮੱਗਰੀ ਜੋੜੋ', editItem:'ਸਮੱਗਰੀ ਸੰਪਾਦਿਤ ਕਰੋ', bulkEdit:'ਸਭ ਸੰਪਾਦਿਤ ਕਰੋ', cancelBulk:'ਰੱਦ', saveAll:'ਸਭ ਸੇਵ', allItems:'ਸਭ ਸਮੱਗਰੀ', lowStock:'ਘੱਟ ਸਟਾਕ', outOfStock:'ਸਟਾਕ ਖਤਮ', unlimited:'ਅਸੀਮਤ', inStock:'ਸਟਾਕ ਵਿੱਚ', quantity:'ਮਾਤਰਾ', unit:'ਇਕਾਈ', alertThreshold:'ਘੱਟ ਸਟਾਕ ਚੇਤਾਵਨੀ', alertWhen:'ਚੇਤਾਵਨੀ ≤', emailAlertSent:'ਈਮੇਲ ਭੇਜੀ', helpText:'ਅਸੀਮਤ ਲਈ ਖਾਲੀ ਛੱਡੋ। 0 ਤੇ ਮੇਨੂ ਤੋਂ ਲੁਕਦਾ ਹੈ।', selectUnit:'ਚੁਣੋ', bulkSaveHint:'ਹੇਠਾਂ ਮਾਤਰਾ ਬਦਲੋ ਫਿਰ ਇੱਕੋ ਵਾਰ ਸੇਵ ਕਰੋ', outStockMsg:'ਸਮੱਗਰੀ ਸਟਾਕ ਖਤਮ', lowStockMsg:'ਸਮੱਗਰੀ ਘੱਟ — ਈਮੇਲ ਭੇਜੀ' },
    analytics: { title:'ਵਿਸ਼ਲੇਸ਼ਣ', totalRevenue:'ਕੁੱਲ ਆਮਦਨ', totalOrders:'ਕੁੱਲ ਆਰਡਰ', avgOrderValue:'ਔਸਤ ਆਰਡਰ ਮੁੱਲ', itemsSold:'ਵੇਚੇ ਗਏ ਆਈਟਮ', revenueChart:'ਸਮੇਂ ਨਾਲ ਆਮਦਨ', topItems:'ਚੋਟੀ ਦੇ ਆਈਟਮ', tablePerf:'ਟੇਬਲ ਕਾਰਗੁਜ਼ਾਰੀ', peakHours:'ਵਿਅਸਤ ਘੰਟੇ', today:'ਅੱਜ', last7:'ਪਿਛਲੇ 7 ਦਿਨ', last30:'ਪਿਛਲੇ 30 ਦਿਨ', last90:'ਪਿਛਲੇ 90 ਦਿਨ', noData:'ਇਸ ਸਮੇਂ ਲਈ ਕੋਈ ਡੇਟਾ ਨਹੀਂ', busiestHour:'ਸਭ ਤੋਂ ਵਿਅਸਤ ਘੰਟਾ', ordersLabel:'ਆਰਡਰ', fromLabel:'ਤੋਂ', toLabel:'ਤੱਕ', qtySold:'ਵੇਚੀ ਮਾਤਰਾ' },
    customer: { selectLang:'ਭਾਸ਼ਾ ਚੁਣੋ', continueMenu:'ਮੇਨੂ ਤੇ ਜਾਓ', skipBrowse:'ਸਿੱਧੇ ਮੇਨੂ', enterDetails:'ਸ਼ੁਰੂ ਕਰੀਏ!', optionalDetails:'ਵਧੀਆ ਤਜਰਬੇ ਲਈ ਜਾਣਕਾਰੀ ਦਿਓ।', yourName:'ਨਾਮ', phoneNumber:'ਫ਼ੋਨ ਨੰਬਰ', optional:'ਵਿਕਲਪਿਕ', addToCart:'ਕਾਰਟ ਵਿੱਚ ਜੋੜੋ', viewCart:'ਕਾਰਟ ਵੇਖੋ', placeOrder:'ਆਰਡਰ ਦਿਓ', placing:'ਆਰਡਰ ਹੋ ਰਿਹਾ...', yourCart:'ਕਾਰਟ', items:'ਆਈਟਮ', orderPlaced:'ਆਰਡਰ ਦਿੱਤਾ!', orderSentKitchen:'ਆਰਡਰ ਰਸੋਈ ਨੂੰ ਭੇਜਿਆ।', orderId:'ਆਰਡਰ ID', orderMore:'ਹੋਰ ਆਰਡਰ', specialInstructions:'ਖ਼ਾਸ ਹਦਾਇਤਾਂ', goesWith:'ਨਾਲ ਚੰਗਾ...', forYou:'ਤੁਹਾਡੇ ਲਈ', total:'ਕੁੱਲ', billSummary:'ਬਿੱਲ ਸਾਰ', scanOrder:'ਸਕੈਨ ਕਰੋ', poweredBy:'QRunch', welcomeBack:'ਵਾਪਸ ਸੁਆਗਤ', returnMenu:'ਮੇਨੂ', emptyCart:'ਕਾਰਟ ਖਾਲੀ', browseMenu:'ਮੇਨੂ ਵੇਖੋ', yourDetails:'ਵੇਰਵੇ', reorderNote:'ਦੁਬਾਰਾ ਆਰਡਰ ਲਈ।', remove:'ਹਟਾਓ', noMenu:'ਮੇਨੂ ਤਿਆਰ ਹੋ ਰਿਹਾ।' }
  },

  es: {
    nav: { dashboard:'Panel', menu:'Constructor de menú', tables:'Mesas y QR', orders:'Pedidos', analytics:'Análisis', inventory:'Inventario', staff:'Personal', soon:'Pronto' },
    common: { add:'Agregar', edit:'Editar', delete:'Eliminar', save:'Guardar', cancel:'Cancelar', update:'Actualizar', logout:'Cerrar sesión', loading:'Cargando...', available:'Disponible', unavailable:'No disponible', exportCSV:'Exportar CSV', refresh:'Actualizar', apply:'Aplicar' },
    menu: { title:'Constructor de menú', addCategory:'Agregar categoría', editCategory:'Editar categoría', addItem:'+ Agregar plato', editItem:'Editar plato', itemName:'Nombre del plato', itemNamePlaceholder:'Ej. Tacos al pastor', description:'Descripción', descPlaceholder:'Describe tu plato...', price:'Precio', photo:'Foto', uploadPhoto:'Subir foto', generateDesc:'Generar con IA', generatingDesc:'Generando...', suggestTags:'Sugerir con IA', suggestingTags:'Sugiriendo...', generateImage:'Generar imagen con IA', generatingImage:'Generando imagen...', dietaryTags:'Etiquetas alimentarias', modifiers:'Modificadores', addGroup:'+ Agregar grupo', addOption:'+ Agregar opción', groupName:'Nombre del grupo', optionLabel:'Etiqueta de opción', extraPrice:'+precio', noCategories:'Sin categorías', noItems:'Sin platos — agrega el primero!', categoryPlaceholder:'Ej. Entradas, Principales, Postres', aiSuggestedTags:'Sugerido por IA', canDeselect:'puedes quitar cualquiera', imageNote:'Puede tardar hasta 60 segundos', selectCategory:'Selecciona categoría', startWithCategory:'Agrega una categoría para empezar' },
    inventory: { title:'Inventario', addItem:'+ Agregar artículo', editItem:'Editar artículo', bulkEdit:'Editar todo', cancelBulk:'Cancelar', saveAll:'Guardar todo', allItems:'Todos los artículos', lowStock:'Stock bajo', outOfStock:'Sin stock', unlimited:'Ilimitado', inStock:'En stock', quantity:'Cantidad', unit:'Unidad', alertThreshold:'Umbral de alerta', alertWhen:'Alerta cuando ≤', emailAlertSent:'Alerta enviada por email', helpText:'Deja en blanco para ilimitado. En 0 se oculta del menú.', selectUnit:'Seleccionar', bulkSaveHint:'Edita las cantidades y guarda todo a la vez', outStockMsg:'artículos sin stock y ocultos del menú', lowStockMsg:'artículos con stock bajo — alerta enviada' },
    analytics: { title:'Análisis', totalRevenue:'Ingresos totales', totalOrders:'Pedidos totales', avgOrderValue:'Valor promedio', itemsSold:'Artículos vendidos', revenueChart:'Ingresos en el tiempo', topItems:'Platos principales', tablePerf:'Rendimiento por mesa', peakHours:'Horas pico', today:'Hoy', last7:'Últimos 7 días', last30:'Últimos 30 días', last90:'Últimos 90 días', noData:'Sin datos para este período', busiestHour:'Hora más ocupada', ordersLabel:'pedidos', fromLabel:'Desde', toLabel:'Hasta', qtySold:'Cant. vendida' },
    customer: { selectLang:'Seleccionar idioma', continueMenu:'Ir al menú', skipBrowse:'Solo explorar', enterDetails:'¡Empecemos!', optionalDetails:'Ingresa tus datos para una experiencia personalizada.', yourName:'Tu nombre', phoneNumber:'Teléfono', optional:'opcional', addToCart:'Añadir al carrito', viewCart:'Ver carrito', placeOrder:'Hacer pedido', placing:'Realizando pedido...', yourCart:'Tu carrito', items:'artículos', orderPlaced:'¡Pedido realizado!', orderSentKitchen:'Tu pedido ha sido enviado a la cocina.', orderId:'ID de pedido', orderMore:'Pedir más', specialInstructions:'Instrucciones especiales', goesWith:'Va bien con...', forYou:'Para ti', total:'Total', billSummary:'Resumen del pedido', scanOrder:'Escanea para ver el menú', poweredBy:'Con tecnología de QRunch', welcomeBack:'Bienvenido de nuevo', returnMenu:'Volviendo al menú en', emptyCart:'Tu carrito está vacío', browseMenu:'Ver menú', yourDetails:'Tus datos', reorderNote:'Solo para actualizaciones de pedidos.', remove:'Quitar', noMenu:'El menú está siendo preparado.' }
  }
};

import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = Object.fromEntries(
  Object.entries(t).map(([lang, translation]) => [lang, { translation }])
);

i18n
  .use(initReactI18next)
  .init({
    resources,
    lng:           localStorage.getItem('qrunch_ui_lang') || 'en',
    fallbackLng:   'en',
    interpolation: { escapeValue: false }
  });

export default i18n;